services:
  - type: web
    name: auralearn-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_TTS_API_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: auralearn-d0548
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
