export const APP_NAME = 'AURA Learn';
export const APP_TAGLINE = 'Your Personal AI University';
export const APP_DESCRIPTION = 'Learn anything with an AI professor that teaches like a real human instructor.';

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Explore Courses', href: '/courses' },
  { label: 'AI Teacher', href: '/ai-teacher' },
  { label: 'Live Classroom', href: '/classroom' },
  { label: 'Coding Lab', href: '/coding-lab' },
  { label: 'Resume Hub', href: '/resume-hub' },
  { label: 'Dashboard', href: '/dashboard' },
  { label: 'Career Roadmaps', href: '/roadmap' },
  { label: 'Certificates', href: '/certificates' },
  { label: 'Community', href: '/community' },
  { label: 'Help Center', href: '/help' },
];

export const COURSE_CATEGORIES = [
  { id: 'programming', label: 'Programming', icon: 'Code2', color: '#6366f1' },
  { id: 'artificial-intelligence', label: 'AI & Machine Learning', icon: 'Brain', color: '#8b5cf6' },
  { id: 'data-science', label: 'Data Science', icon: 'BarChart3', color: '#06b6d4' },
  { id: 'mathematics', label: 'Mathematics', icon: 'Sigma', color: '#f59e0b' },
  { id: 'science', label: 'Science', icon: 'Flask', color: '#10b981' },
  { id: 'engineering', label: 'Engineering', icon: 'Settings2', color: '#ef4444' },
  { id: 'business', label: 'Business', icon: 'Briefcase', color: '#3b82f6' },
  { id: 'finance', label: 'Finance', icon: 'TrendingUp', color: '#14b8a6' },
  { id: 'design', label: 'Design', icon: 'Palette', color: '#ec4899' },
  { id: 'languages', label: 'Languages', icon: 'Languages', color: '#a855f7' },
  { id: 'cybersecurity', label: 'Cybersecurity', icon: 'Shield', color: '#22c55e' },
  { id: 'cloud-computing', label: 'Cloud Computing', icon: 'Cloud', color: '#0ea5e9' },
];

export const LEVELS = [
  { id: 'beginner', label: 'Beginner', color: '#22c55e' },
  { id: 'intermediate', label: 'Intermediate', color: '#f59e0b' },
  { id: 'advanced', label: 'Advanced', color: '#ef4444' },
  { id: 'expert', label: 'Expert', color: '#8b5cf6' },
];

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
];

export const VOICE_OPTIONS = [
  { id: 'male', label: 'Male Voice', gender: 'male' },
  { id: 'female', label: 'Female Voice', gender: 'female' },
];

export * from './syllabi';

export const AMBIENT_SOUNDS = [
  { id: 'none', label: 'None', icon: 'VolumeX' },
  { id: 'classroom', label: 'Classroom', icon: 'School' },
  { id: 'rain', label: 'Rain', icon: 'CloudRain' },
  { id: 'library', label: 'Library', icon: 'BookOpen' },
  { id: 'instrumental', label: 'Soft Music', icon: 'Music' },
  { id: 'white-noise', label: 'White Noise', icon: 'Waves' },
  { id: 'nature', label: 'Nature', icon: 'TreePine' },
  { id: 'coffee-shop', label: 'Coffee Shop', icon: 'Coffee' },
];

export const MOCK_COURSES = [
  {
    id: '1',
    title: 'Complete Python Programming',
    description: 'Master Python from zero to advanced with hands-on projects and real-world applications.',
    category: 'programming' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/python.jpg',
    color: '#3B82F6',
    emoji: '🐍',
    instructor: { name: 'Dr. Sarah Chen', avatar: '/avatars/teacher1.jpg', title: 'AI Research Scientist' },
    rating: 4.8,
    enrolledStudents: 15420,
    totalLessons: 120,
    totalDuration: 3600,
    price: 0,
    tags: ['Python', 'Programming', 'Beginner Friendly'],
  },
  {
    id: '2',
    title: 'Deep Learning & Neural Networks',
    description: 'Build neural networks from scratch and master deep learning with PyTorch and TensorFlow.',
    category: 'artificial-intelligence' as const,
    level: 'advanced' as const,
    thumbnail: '/courses/deep-learning.jpg',
    color: '#8B5CF6',
    emoji: '🧠',
    instructor: { name: 'Prof. Alex Kumar', avatar: '/avatars/teacher2.jpg', title: 'Deep Learning Engineer' },
    rating: 4.9,
    enrolledStudents: 8930,
    totalLessons: 85,
    totalDuration: 4800,
    price: 0,
    tags: ['Deep Learning', 'Neural Networks', 'PyTorch', 'TensorFlow'],
  },
  {
    id: '3',
    title: 'Full-Stack Web Development',
    description: 'Build modern web applications with React, Next.js, Node.js, and TypeScript.',
    category: 'programming' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/webdev.jpg',
    color: '#06B6D4',
    emoji: '🌐',
    instructor: { name: 'Maria Rodriguez', avatar: '/avatars/teacher3.jpg', title: 'Full-Stack Developer' },
    rating: 4.7,
    enrolledStudents: 12300,
    totalLessons: 150,
    totalDuration: 5400,
    price: 0,
    tags: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Full-Stack'],
  },
  {
    id: '4',
    title: 'Data Science & Analytics',
    description: 'Learn data analysis, visualization, statistics, and machine learning with Python.',
    category: 'data-science' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/datascience.jpg',
    color: '#10B981',
    emoji: '📊',
    instructor: { name: 'Dr. James Wilson', avatar: '/avatars/teacher4.jpg', title: 'Data Scientist' },
    rating: 4.6,
    enrolledStudents: 18750,
    totalLessons: 95,
    totalDuration: 3200,
    price: 0,
    tags: ['Data Science', 'Python', 'Statistics', 'Machine Learning'],
  },
  {
    id: '5',
    title: 'Cybersecurity Fundamentals',
    description: 'Protect systems and networks from cyber threats with hands-on security training.',
    category: 'cybersecurity' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/cybersecurity.jpg',
    color: '#22C55E',
    emoji: '🛡️',
    instructor: { name: 'Marcus Johnson', avatar: '/avatars/teacher5.jpg', title: 'Security Engineer' },
    rating: 4.8,
    enrolledStudents: 7650,
    totalLessons: 70,
    totalDuration: 2800,
    price: 0,
    tags: ['Cybersecurity', 'Network Security', 'Ethical Hacking'],
  },
  {
    id: '6',
    title: 'Business Strategy & Management',
    description: 'Develop strategic thinking and management skills for modern businesses.',
    category: 'business' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/business.jpg',
    color: '#3B82F6',
    emoji: '💼',
    instructor: { name: 'Prof. Emily Park', avatar: '/avatars/teacher6.jpg', title: 'Business Strategist' },
    rating: 4.5,
    enrolledStudents: 5430,
    totalLessons: 60,
    totalDuration: 2400,
    price: 0,
    tags: ['Business', 'Strategy', 'Management', 'Leadership'],
  },
  {
    id: '7',
    title: 'Calculus & Linear Algebra Mastery',
    description: 'Master the mathematical foundations of AI and engineering with interactive visualizations.',
    category: 'mathematics' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/mathematics.jpg',
    color: '#F59E0B',
    emoji: '∑',
    instructor: { name: 'Dr. Priya Nair', avatar: '/avatars/teacher7.jpg', title: 'Professor of Mathematics' },
    rating: 4.7,
    enrolledStudents: 9200,
    totalLessons: 88,
    totalDuration: 3100,
    price: 0,
    tags: ['Calculus', 'Linear Algebra', 'Mathematics', 'AI Foundations'],
  },
  {
    id: '8',
    title: 'Cloud Computing & AWS',
    description: 'Deploy scalable applications on AWS with hands-on labs covering EC2, S3, Lambda, and more.',
    category: 'cloud-computing' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/cloud.jpg',
    color: '#0EA5E9',
    emoji: '☁️',
    instructor: { name: 'Ryan Mitchell', avatar: '/avatars/teacher8.jpg', title: 'AWS Solutions Architect' },
    rating: 4.8,
    enrolledStudents: 11200,
    totalLessons: 92,
    totalDuration: 3800,
    price: 0,
    tags: ['AWS', 'Cloud', 'DevOps', 'Serverless'],
  },
  {
    id: '9',
    title: 'UI/UX Design Masterclass',
    description: 'Create stunning user interfaces and experiences with Figma, design systems, and usability principles.',
    category: 'design' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/design.jpg',
    color: '#EC4899',
    emoji: '🎨',
    instructor: { name: 'Sofia Yamamoto', avatar: '/avatars/teacher9.jpg', title: 'Senior UX Designer' },
    rating: 4.9,
    enrolledStudents: 14800,
    totalLessons: 80,
    totalDuration: 2900,
    price: 0,
    tags: ['UI/UX', 'Figma', 'Design Systems', 'Prototyping'],
  },
  {
    id: '10',
    title: 'Financial Modeling & Investment',
    description: 'Build financial models, analyze markets, and make data-driven investment decisions.',
    category: 'finance' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/finance.jpg',
    color: '#14B8A6',
    emoji: '📈',
    instructor: { name: 'David Chen', avatar: '/avatars/teacher10.jpg', title: 'CFA & Portfolio Manager' },
    rating: 4.6,
    enrolledStudents: 6340,
    totalLessons: 65,
    totalDuration: 2600,
    price: 0,
    tags: ['Finance', 'Investment', 'Financial Modeling', 'Excel'],
  },
  {
    id: '11',
    title: 'Natural Language Processing',
    description: 'Build AI language models, chatbots, and text analysis systems with transformers and BERT.',
    category: 'artificial-intelligence' as const,
    level: 'advanced' as const,
    thumbnail: '/courses/nlp.jpg',
    color: '#A855F7',
    emoji: '💬',
    instructor: { name: 'Dr. Lisa Wang', avatar: '/avatars/teacher11.jpg', title: 'NLP Research Lead' },
    rating: 4.8,
    enrolledStudents: 5870,
    totalLessons: 75,
    totalDuration: 3400,
    price: 0,
    tags: ['NLP', 'Transformers', 'BERT', 'ChatGPT API', 'LLMs'],
  },
  {
    id: '12',
    title: 'Physics: Mechanics to Quantum',
    description: 'Journey through classical mechanics, electromagnetism, and quantum physics with interactive simulations.',
    category: 'science' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/physics.jpg',
    color: '#EF4444',
    emoji: '⚛️',
    instructor: { name: 'Prof. Neil Roberts', avatar: '/avatars/teacher12.jpg', title: 'Quantum Physicist' },
    rating: 4.7,
    enrolledStudents: 8100,
    totalLessons: 110,
    totalDuration: 4200,
    price: 0,
    tags: ['Physics', 'Quantum Mechanics', 'Science', 'Engineering'],
  },
];

export const FAQ_ITEMS = [
  {
    question: 'How does AI teaching work?',
    answer: 'AURA Learn uses advanced AI agents that work together to create personalized learning experiences. The AI analyzes your learning style, progress, and goals to adapt teaching in real-time.',
  },
  {
    question: 'Can I learn programming without experience?',
    answer: 'Yes! Our platform supports learners at all levels. The AI automatically adjusts the curriculum to your skill level, starting from basics if you are a complete beginner.',
  },
  {
    question: 'Is the platform available in multiple languages?',
    answer: 'Yes, AURA Learn supports multiple languages. All lessons, quizzes, notes, and AI conversations automatically adapt to your selected language.',
  },
  {
    question: 'How are certificates issued?',
    answer: 'Certificates are automatically generated upon course completion with a unique verification ID. They can be shared on LinkedIn and verified by employers.',
  },
  {
    question: 'Does the AI remember my learning history?',
    answer: 'Yes, the AI maintains a comprehensive learning profile, remembering your progress, strengths, weaknesses, and preferences to personalize every lesson.',
  },
  {
    question: 'Can I ask questions during a lesson?',
    answer: 'Absolutely! You can interrupt any lesson with questions via voice or text. The AI will answer on a side panel and then resume teaching seamlessly.',
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Alex Thompson',
    role: 'Software Engineer',
    avatar: '/avatars/student1.jpg',
    content: 'AURA Learn completely transformed how I learn. The AI teacher explains concepts better than any human instructor I have had.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Data Scientist',
    avatar: '/avatars/student2.jpg',
    content: 'The coding lab with real-time AI guidance helped me build production-ready skills. Highly recommended for aspiring developers.',
    rating: 5,
  },
  {
    id: '3',
    name: 'James Miller',
    role: 'AI Researcher',
    avatar: '/avatars/student3.jpg',
    content: 'The deep learning course with interactive whiteboard teaching made complex concepts intuitive. The AI assistant is incredible.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Sofia Garcia',
    role: 'Product Manager',
    avatar: '/avatars/student4.jpg',
    content: 'Being able to learn in Spanish with full AI support is amazing. The automated notes and flashcards save me hours of study time.',
    rating: 5,
  },
];

export const TEACHER_STYLES = [
  {
    id: 'professor',
    name: 'Professor',
    title: 'The Classic Educator',
    tagline: 'Structured, thorough, and comprehensive teaching with deep explanations.',
    description: 'Like a university professor, I teach with well-structured lessons, building from fundamentals to advanced concepts. I use formal explanations, cite research, and ensure you have a deep theoretical understanding before moving to practice.',
    icon: 'GraduationCap',
    color: '#6366f1',
    voiceStyle: 'Formal, articulate, measured',
    teachingApproach: 'Structured',
    explanationDepth: 'comprehensive' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'moderate' as const,
  },
  {
    id: 'coach',
    name: 'Coach',
    title: 'The Motivational Mentor',
    tagline: 'Practical, hands-on learning with real-world projects and encouragement.',
    description: 'I focus on practical application and building real projects. My teaching is action-oriented with lots of exercises, challenges, and encouragement. I push you to code, build, and create while providing supportive guidance.',
    icon: 'Zap',
    color: '#f59e0b',
    voiceStyle: 'Energetic, encouraging, direct',
    teachingApproach: 'Hands-on',
    explanationDepth: 'moderate' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'fast' as const,
  },
  {
    id: 'friend',
    name: 'Friend',
    title: 'The Friendly Guide',
    tagline: 'Conversational, relatable teaching with humor and everyday analogies.',
    description: 'Learning should feel natural and fun! I teach like a knowledgeable friend explaining things over coffee. I use casual language, humor, and relatable analogies. No question is too silly — I create a safe, judgment-free learning space.',
    icon: 'Heart',
    color: '#ec4899',
    voiceStyle: 'Warm, casual, friendly',
    teachingApproach: 'Conversational',
    explanationDepth: 'basic' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: true,
    encourageQuestions: true,
    pace: 'slow' as const,
  },
  {
    id: 'expert',
    name: 'Expert',
    title: 'The Industry Veteran',
    tagline: 'Advanced insights, best practices, and professional-grade teaching.',
    description: 'I teach like a senior engineer or industry expert sharing years of experience. I focus on best practices, design patterns, performance optimization, and production-ready code. Perfect for experienced learners who want to level up.',
    icon: 'Brain',
    color: '#8b5cf6',
    voiceStyle: 'Authoritative, precise, confident',
    teachingApproach: 'Advanced',
    explanationDepth: 'deep' as const,
    useAnalogies: false,
    useExamples: true,
    useHumor: false,
    encourageQuestions: false,
    pace: 'fast' as const,
  },
  {
    id: 'simplifier',
    name: 'Simplifier',
    title: 'The Clear Explainer',
    tagline: 'Complex topics made simple with visual explanations and step-by-step breakdowns.',
    description: 'I specialize in taking the most complex topics and breaking them down into simple, digestible pieces. I use visual explanations, step-by-step breakdowns, and the "explain like I\'m 5" approach. Perfect for beginners or tough topics.',
    icon: 'BookOpen',
    color: '#06b6d4',
    voiceStyle: 'Patient, clear, slow-paced',
    teachingApproach: 'Step-by-step',
    explanationDepth: 'basic' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'slow' as const,
  },
] as const;

export const ACHIEVEMENTS_LIST = [
  {
    id: 'first-lesson',
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: 'Footprints',
    xpReward: 50,
    category: 'learning' as const,
  },
  {
    id: 'streak-7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day learning streak',
    icon: 'Flame',
    xpReward: 200,
    category: 'streak' as const,
  },
  {
    id: 'quiz-perfect',
    title: 'Perfect Score',
    description: 'Get 100% on any quiz',
    icon: 'Award',
    xpReward: 150,
    category: 'quiz' as const,
  },
  {
    id: 'code-master',
    title: 'Code Master',
    description: 'Complete 10 coding exercises',
    icon: 'Code2',
    xpReward: 300,
    category: 'coding' as const,
  },
  {
    id: 'course-complete',
    title: 'Graduate',
    description: 'Complete an entire course',
    icon: 'GraduationCap',
    xpReward: 500,
    category: 'learning' as const,
  },
  {
    id: 'project-pro',
    title: 'Project Pro',
    description: 'Complete 5 projects',
    icon: 'FolderKanban',
    xpReward: 400,
    category: 'project' as const,
  },
];

export const ROADMAPS = [
  {
    id: 'frontend-dev',
    title: 'Frontend Developer',
    description: 'Master modern frontend development with React, TypeScript, and modern CSS',
    courses: ['HTML/CSS Basics', 'JavaScript Fundamentals', 'React Mastery', 'TypeScript Deep Dive', 'Advanced CSS'],
    duration: '6-8 months',
    level: 'beginner' as const,
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    description: 'Become a data scientist with Python, statistics, and machine learning',
    courses: ['Python Programming', 'Statistics & Probability', 'Machine Learning', 'Deep Learning', 'Data Engineering'],
    duration: '8-12 months',
    level: 'beginner' as const,
  },
  {
    id: 'ai-engineer',
    title: 'AI Engineer',
    description: 'Build production AI systems with deep learning and NLP',
    courses: ['Python Advanced', 'Deep Learning', 'NLP', 'Computer Vision', 'MLOps'],
    duration: '10-14 months',
    level: 'intermediate' as const,
  },
  {
    id: 'fullstack-dev',
    title: 'Full-Stack Developer',
    description: 'Build complete web applications from frontend to backend',
    courses: ['Frontend Development', 'Backend Development', 'Database Design', 'DevOps Basics', 'Cloud Deployment'],
    duration: '8-10 months',
    level: 'beginner' as const,
  },
];
